import type { SpeechAssetTierId } from '../../shared/speech-asset-ipc';

/** Fixed application-owned layout. No archive may choose another component's destination. */
export const SPEECH_ASSET_TARGETS = {
  'voice-runtime': 'voice-runtime',
  'speech-input': 'speech-input-runtime',
  'bert-japanese': 'bert-japanese',
  'voice-ireina': 'voice-ireina',
  'genie-tts': 'genie-tts',
  'genie-data': 'genie-data',
  'voice-genie-mika': 'voice-genie-mika',
  'genie-language-data': 'genie-language-data',
  'voice-genie-feibi': 'voice-genie-feibi',
  'voice-genie-thirtyseven': 'voice-genie-thirtyseven',
} as const satisfies Record<SpeechAssetTierId, string>;
export type SpeechAssetTarget = (typeof SPEECH_ASSET_TARGETS)[SpeechAssetTierId];
const GENIE_VOICE_FILES = [
  'tts_models/t2s_encoder_fp32.onnx',
  'tts_models/t2s_encoder_fp32.bin',
  'tts_models/t2s_first_stage_decoder_fp32.onnx',
  'tts_models/t2s_stage_decoder_fp32.onnx',
  'tts_models/t2s_shared_fp16.bin',
  'tts_models/vits_fp32.onnx',
  'tts_models/vits_fp16.bin',
  'tts_models/prompt_encoder_fp32.onnx',
  'tts_models/prompt_encoder_fp16.bin',
  'prompt_wav.json',
  'LICENSE.txt',
] as const;
export const REQUIRED_TARGET_FILES: Readonly<Record<SpeechAssetTarget, readonly string[]>> = {
  'genie-language-data': [
    'ChineseG2P/opencpop-strict.txt',
    'ChineseG2P/polyphonic.pickle',
    'EnglishG2P/checkpoint20.npz',
    'EnglishG2P/engdict_cache.pickle',
    'EnglishG2P/namedict_cache.pickle',
    'EnglishG2P/engdict-hot.rep',
    'EnglishG2P/wordsegment/bigrams.txt',
    'EnglishG2P/wordsegment/unigrams.txt',
    'EnglishG2P/wordsegment/words.txt',
    'EnglishG2P/taggers/averaged_perceptron_tagger_eng/averaged_perceptron_tagger_eng.classes.json',
    'EnglishG2P/taggers/averaged_perceptron_tagger_eng/averaged_perceptron_tagger_eng.tagdict.json',
    'EnglishG2P/taggers/averaged_perceptron_tagger_eng/averaged_perceptron_tagger_eng.weights.json',
    'LICENSE.txt',
  ],
  'voice-genie-feibi': [...GENIE_VOICE_FILES, 'prompt_wav/zh_vo_Main_Linaxita_2_1_10_26.wav'],
  'voice-genie-thirtyseven': [
    ...GENIE_VOICE_FILES,
    'prompt_wav/En_play_hero3066_fightingvoc_19.wav',
  ],
  'voice-runtime': ['python/python.exe', 'ireina_tts_service.py'],
  'speech-input-runtime': ['models/sensevoice/model.int8.onnx', 'models/sensevoice/tokens.txt'],
  'bert-japanese': ['model_fp16.onnx', 'config.json', 'tokenizer.json'],
  'voice-ireina': ['ireina_e100_s16040.onnx', 'config.json', 'style_vectors.npy', 'LICENSE.txt'],
  'genie-tts': [
    'python/python.exe',
    'fpnf_genie_service.py',
    'python/Lib/site-packages/genie_tts/__init__.py',
    'LICENSE.txt',
  ],
  'genie-data': [
    'chinese-hubert-base/chinese-hubert-base.onnx',
    'chinese-hubert-base/chinese-hubert-base_weights_fp16.bin',
    'speaker_encoder.onnx',
    'LICENSE.txt',
  ],
  'voice-genie-mika': [
    'tts_models/t2s_encoder_fp32.onnx',
    'tts_models/t2s_encoder_fp32.bin',
    'tts_models/t2s_first_stage_decoder_fp32.onnx',
    'tts_models/t2s_stage_decoder_fp32.onnx',
    'tts_models/t2s_shared_fp16.bin',
    'tts_models/vits_fp32.onnx',
    'tts_models/vits_fp16.bin',
    'tts_models/prompt_encoder_fp32.onnx',
    'tts_models/prompt_encoder_fp16.bin',
    'prompt_wav.json',
    'prompt_wav/917575.wav',
    'LICENSE.txt',
  ],
};
